# 只保 LLVM/GCC + 少量高质量编译器项目；全部是官方 RSS/Atom
rss:
  # ---- LLVM 家族 ----
  - {name: llvm-discourse-announcements, url: https://discourse.llvm.org/c/announce/46.rss, tags: {projects: [LLVM], topics: [Announcements, Release]}, priority: high}
  - {name: llvm-discourse-mlir,         url: https://discourse.llvm.org/c/mlir/31.rss,      tags: {projects: [LLVM, MLIR], topics: [IR/Pass]}, priority: medium}
  - {name: llvm-blog,                   url: https://blog.llvm.org/index.xml,               tags: {projects: [LLVM], topics: [Project News]},  priority: medium}
  - {name: llvm-weekly,                 url: http://llvmweekly.org/rss.xml,                 tags: {projects: [LLVM], topics: [Weekly]},        priority: high}
  - {name: llvm-releases,               url: https://github.com/llvm/llvm-project/releases.atom, tags: {projects: [LLVM], topics: [Release]}, priority: high}
  - {name: llvm-commits,                url: https://github.com/llvm/llvm-project/commits/main.atom, tags: {projects: [LLVM], topics: [Commits]}, priority: low}
  - {name: llvm-prs,                url: https://github.com/llvm/llvm-project/pulls.atom, tags: {projects: [LLVM], topics: [PRs]}, priority: medium}
  - {name: llvm-issues,                url: https://github.com/llvm/llvm-project/issues.atom, tags: {projects: [LLVM], topics: [Issues]}, priority: low}

  # ---- GCC 家族 ----
  - {name: gcc-announce, url: https://inbox.sourceware.org/gcc-announce/new.atom, tags: {projects: [GCC], topics: [Announcements, Release]}, priority: high}
  - {name: gcc-patches,  url: https://inbox.sourceware.org/gcc-patches/new.atom,  tags: {projects: [GCC], topics: [Patches]},               priority: medium}
  - {name: gcc-commits,  url: https://github.com/gcc-mirror/gcc/commits/master.atom, tags: {projects: [GCC], topics: [Commits]}, priority: low}
  - {name: gcc-releases, url: https://github.com/gcc-mirror/gcc/releases.atom,    tags: {projects: [GCC], topics: [Release]},               priority: high}
  - {name: gcc-prs, url: https://github.com/gcc-mirror/gcc/pulls.atom,    tags: {projects: [GCC], topics: [PRs]},               priority: medium}
  - {name: gcc-issues, url: https://github.com/gcc-mirror/gcc/issues.atom,    tags: {projects: [GCC], topics: [Issues]},               priority: low}

  # ---- 其他编译器（少量且官方）----
  - {name: rust-blog,    url: https://blog.rust-lang.org/feed.xml,                tags: {projects: [Rust], topics: [Project News]}, priority: medium}
  - {name: swift-forums, url: https://forums.swift.org/latest.rss,                tags: {projects: [Swift], topics: [Frontend]},     priority: medium}
  - {name: v8-blog,      url: https://v8.dev/blog.atom,                           tags: {projects: [V8], topics: [Backend/Target]},  priority: medium}
  - {name: graalvm-blog, url: https://www.graalvm.org/feed.xml,                   tags: {projects: [GraalVM], topics: [JIT]},        priority: medium}
  - {name: wasmtime,     url: https://bytecodealliance.org/feed.xml,              tags: {projects: [Cranelift/Wasmtime], topics: [WASM]}, priority: medium}
  - {name: zig-news,     url: https://ziglang.org/news/index.xml,                 tags: {projects: [Zig], topics: [Toolchain]},      priority: low}

allow_hosts:
  - discourse.llvm.org
  - blog.llvm.org
  - llvmweekly.org
  - inbox.sourceware.org
  - github.com
  - blog.rust-lang.org
  - forums.swift.org
  - v8.dev
  - graalvm.org
  - bytecodealliance.org
  - ziglang.org

github_repos:
  - {repo: llvm/llvm-project, types: [pulls, issues, releases, commits]}
  - {repo: gcc-mirror/gcc,    types: [releases, commits]}